QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT_LIBCPP_ABI_TAG = 
QT.global.enabled_features = shared c++11 c++14 c++17 c++1z c99 c11 reduce_relocations signaling_nan thread future concurrent dbus shared shared c++11 c++14 c++17 c++1z reduce_exports reduce_relocations
QT.global.disabled_features = static cross_compile pkg-config debug_and_release separate_debug_info appstore-compliant simulator_and_device rpath force_asserts framework c++20 c++2a c++2b c++2b wasm-simd128 wasm-exceptions zstd openssl-linked opensslv11 opensslv30
QT.global.disabled_features += release build_all
QT_CONFIG += shared no-pkg-config c++11 c++14 c++17 c++1z reduce_exports reduce_relocations release
CONFIG +=  shared plugin_manifest
QT_VERSION = 6.5.3
QT_MAJOR_VERSION = 6
QT_MINOR_VERSION = 5
QT_PATCH_VERSION = 3

QT_LIBINFIX = AndroidEmu
QT_APPLE_CLANG_MAJOR_VERSION = 13
QT_APPLE_CLANG_MINOR_VERSION = 1
QT_APPLE_CLANG_PATCH_VERSION = 6
QT_MAC_SDK_VERSION = 12.3
QMAKE_MACOSX_DEPLOYMENT_TARGET = 11.0
QT_ARCHS = $$QT_ARCH
QT_EDITION = Open Source
