QT_PLUGIN.qdarwincontactspermissionAndroidEmu.TYPE = permissions
QT_PLUGIN.qdarwincontactspermissionAndroidEmu.EXTENDS = -
QT_PLUGIN.qdarwincontactspermissionAndroidEmu.DEPENDS = core
QT_PLUGIN.qdarwincontactspermissionAndroidEmu.CLASS_NAME = QDarwinContactsPermissionPlugin
QT_PLUGIN.qdarwincontactspermissionAndroidEmu.module_config = v2 staticlib
QT_PLUGINS += qdarwincontactspermissionAndroidEmu
QT_PLUGIN.qdarwincontactspermission.usage_descriptions = NSContactsUsageDescription
QT_PLUGIN.qdarwincontactspermission.request_flag = 